### ISSUE TITLE
Question about corMirnaRna()

### ISSUE THREAD

**Issue by athul09** [Mercedeh66/mirTarRnaSeq#2]
Hi,

While using the corMirnaRna function, my output shows NA values and doesn't seem to do any correlation analysis. I wanted to ask if there is any other specific information required in the inputs, or if there is an example of the code apart from what is shown in the manuals so I can make sure that I have the right code.

Sorry for any troubles and any help would be appreciated!

**Comment by Mercedeh66** [comment]
Can you please be more specific? what is your input? How does your dataset look like? I can't answer your question otherwise.
