### ISSUE TITLE
Memory requirements and parallelizing code

### ISSUE THREAD

**Issue by diwasri** [Mercedeh66/mirTarRnaSeq#3]
Hi, I am using the mirTarRnaSeq package to look at the miRNA-mRNA interactions in human data. I want to do the univariate analysis using the gaussian distribution. When I do it for one miRNA then the process is quick. However, as mentioned in the paper, when I want to do it for all the miRNA, the process seems to be very long and memory intensive. Do you have a recommendation of the memory and time needed to compare about 400 miRNAs?

I modified the script hoping that I can parallelize it as follows

`library(parallel)

# Define the number of cores to use
num_cores <- detectCores() - 1

# Define your function
run_model <- function(miRNA) {
  runModels(Combine, geneVariant, miRNA, family = glm_gaussian(), scale = 100)
}

# Parallelize the computation
results <- mclapply(miRNA_select, run_model, mc.cores = num_cores)

# Assuming results is a list of data frames or similar structure
# Combine the results into a single data frame
combined_results <- do.call(rbind, results)

# Save the results to a CSV file
write.csv(combined_results, "results.csv", row.names = FALSE)`

Please advice.
Thanks
Meenu

**Comment by Mercedeh66** [comment]
Hi, so it really depends on the capabilities of your machine. Maybe try running it on a cluster? 
I have tried for around 45 miRNAs interaction with each other and it takes close to 10 minutes.
Your parallelization approach seems ok though!
I hope this helps!

**Comment by Mercedeh66** [comment]
I also just realized you are running the function per miRNA you should do for a list of miRNAs. If you are trying to run it independently you need to use the runModel() not runModels()! Hope that clears things up a bit.

**Comment by diwasri** [comment]
Thank you! 

My miRNA_select is a list of miRNAs. So, I should be using runModels(), right? Also, how would I get the output in a format that I can then use for downstream analysis. I see that the blaGaus is a list of lists that has "'is_significant''genes''pvalues''all_models''AICvalues''select_mRNA''select_miRNA''combination'". Just like you have it in the paper, I would like to have a csv file with pvalues and FDR for all the miRNA-mRNA interactions. Any help would be greatly appreciated.

**Comment by Mercedeh66** [comment]
"So, I should be using runModels(), right?" 
Yes that is correct. 

"pvalues and FDR for all the miRNA-mRNA interactions", "blaGaus[["pvalues"]]" will give you your p values, you can save it as a data.frame with added miRNA interactions that are stored and ordered at blaGaus[["select_miRNA"]] and blaGaus[["select_mRNA"]] and then run p.adjust() fun on the pvalues and put it in a new column or variable "p.adjust(blaGaus[["pvalues"]],method = "fdr")". 

"I would like to have a csv file", for writing a CSV file you can easily use the  write.csv() fun on your data.frame that you made above. Feel free to always use ? before the function name to get the details on how to use them.

Hope all your questions are answered.

**Comment by Mercedeh66** [comment]
I am assuming this issue is resolved pls feel free to contact me if you have additional issues.
